apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: client01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto-8500
  template:
    metadata:
      labels:
        app: mosquitto-8500
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:2.0
        ports:
        - containerPort: 1883 # MQTT broker port
        - containerPort: 9001 # Optional: WebSocket port for MQTT
        readinessProbe:
            tcpSocket:
              port: 1883
            initialDelaySeconds: 5
            periodSeconds: 5
        volumeMounts:
        - name: mosquitto-config-8500
          mountPath: /mosquitto/config
      volumes:
      - name: mosquitto-config-8500
        configMap:
          name: mosquitto-config-8500
