apiVersion: v1
kind: Service
metadata:
  name: forwarder-service
  namespace: client01
spec:
  type: NodePort
  selector:
    app: forwarder
  ports:
    - port: 8081         # Port that forwarder listens on
      targetPort: 8081    # Forward traffic to this container port
      nodePort: 30081     # NodePort to access forwarder externally
