# permissions for end users to edit forwarders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: jonobridge
    app.kubernetes.io/managed-by: kustomize
  name: forwarder-editor-role
rules:
- apiGroups:
  - jonobridge.dwim.mx
  resources:
  - forwarders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jonobridge.dwim.mx
  resources:
  - forwarders/status
  verbs:
  - get
