# permissions for end users to view jonobridges.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: jonobridge
    app.kubernetes.io/managed-by: kustomize
  name: jonobridge-viewer-role
rules:
- apiGroups:
  - jonobridge.dwim.mx
  resources:
  - jonobridges
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - jonobridge.dwim.mx
  resources:
  - jonobridges/status
  verbs:
  - get
