# permissions for end users to edit jonobridges.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: jonobridge
    app.kubernetes.io/managed-by: kustomize
  name: jonobridge-editor-role
rules:
- apiGroups:
  - jonobridge.dwim.mx
  resources:
  - jonobridges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jonobridge.dwim.mx
  resources:
  - jonobridges/status
  verbs:
  - get
