---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.4
  name: jonobridges.jonobridge.dwim.mx
spec:
  group: jonobridge.dwim.mx
  names:
    kind: Jonobridge
    listKind: JonobridgeList
    plural: jonobridges
    singular: jonobridge
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Jonobridge is the Schema for the jonobridge API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: JonobridgeSpec defines the desired state of Jonobridge
            properties:
              localAddress:
                type: string
              remoteAddress:
                type: string
            required:
            - localAddress
            - remoteAddress
            type: object
          status:
            description: JonobridgeStatus defines the observed state of Jonobridge
            properties:
              connectedClients:
                type: integer
            required:
            - connectedClients
            type: object
        type: object
    served: true
    storage: true
