apiVersion: v1
kind: Service
metadata:
  name: meitrackbridge-service
  namespace: client01
spec:
  type: LoadBalancer
  selector:
    app: meitrackbridge
  ports:
    - name: http               # Name for the 8080 port
      port: 8080               # Port that jonobridge listens on
      targetPort: 8080         # Forward traffic to this container port
      nodePort: 30080          # NodePort to access jonobridge externally on 8080
    - name: tcp                # Name for the 8500 port
      port: 8500               # Additional port for jonobridge
      targetPort: 8500         # Forward traffic to this container port
      nodePort: 30085          # NodePort to access jonobridge externally on 8500
